CREATE TYPE mass_unit AS ENUM ('kg', 'lb');

CREATE TABLE animal (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  kind varchar(100),
  breed varchar(100),
  birthdate timestamp DEFAULT now()
);

CREATE TABLE weighing (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  weight float NOT NULL,
  unit mass_unit DEFAULT 'kg',
  weighed_at timestamp default now(),

  animal_id integer REFERENCES animal(id)
);
